language: ruby

rvm:
  - 2.7
  - 2.6
  - 2.5
  - 2.4
  - 2.3
  
branches:
  only:
    - add_tests
  
script:
  - ruby -e "p RUBY_VERSION"
  - ruby ./tests/tc_pyra.rb --verbose

after_success:
  - echo == ALL TESTS PASSED ==

after_failure:
  - echo == FAILURE ==